## 应用名称
#spring.application.name=test
## 应用服务 WEB 访问端口
#server.port=8080
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mapper/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.test.mybatis.entity
#type: com.alibaba.druid.pool.DruidDataSource
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/test
## 数据库用户名&密码：
#spring.datasource.username=root
#spring.datasource.password=root

server:
  port: 8080
spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 10MB
logging:
  level:
    com.zhiyou100.hospital-zt.mapper : debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean.User
